name: be_rich_app
description: "A solução de todos os problemas financeiros."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  fl_chart: 0.68.0
  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/beRichLogo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/beRichLogo.png